# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-07 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200206_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to=posts.models.upload_location, width_field=200),
        ),
    ]
